### ISSUE TITLE
Windows 11

### ISSUE THREAD

**Issue by Jibbleibble** [Sauceke/LoveMachine#119]
BepInEx Does not support windows 11

**Comment by Sauceke** [comment]
Do you see either of these files?
- `output_log.txt` in the game folder
- `LogOutput.log` in the BepInEx folder inside the game folder

If you do, can you attach them please.

**Comment by Sauceke** [comment]
Windows 11 isn't the issue here, I tested the plugin on a Windows 11 machine and it ran perfectly.
Either your BepInEx installation is broken or something is conflicting with it. I recommend installing the latest [HF patch](https://www.patreon.com/posts/46339224) if you haven't already, as it will find and fix most such problems automatically. You can also install LoveMachine from the HF patch installer (though it's an outdated version).

**Comment by Sauceke** [comment]
Is the issue resolved? Can I close this ticket?

**Comment by Sauceke** [comment]
Assuming to be resolved.
